"""Synthetic construction records for the fictional Brace Electrical business."""
PROJECTS = {
    "INV-1042": dict(
        code="BE-241",
        name="Newstead Exchange",
        stage="Level 02 · Office fit-out",
        location="Newstead, Brisbane",
        foreman="Daniel Cruz",
        initials="DC",
        scope="Lighting rough-in",
        docket="LD-241-09",
        received="2026-10-07",
        drawing="E-201",
        variation=None,
    ),
    "INV-1043": dict(
        code="BE-238",
        name="Woolloongabba Medical",
        stage="Tenancy 04 · Medical fit-out",
        location="Woolloongabba, Brisbane",
        foreman="Mia Chen",
        initials="MC",
        scope="After-hours switchboard works",
        docket="LD-238-17",
        received="2026-10-06",
        drawing="E-104",
        variation=None,
    ),
    "INV-1044": dict(
        code="BE-246",
        name="Teneriffe Workrooms",
        stage="Ground floor · Commercial",
        location="Teneriffe, Brisbane",
        foreman="Daniel Cruz",
        initials="DC",
        scope="Data & communications rough-in",
        docket="LD-246-03",
        received="2026-10-07",
        drawing="E-302",
        variation=None,
    ),
    "INV-1045": dict(
        code="BE-232",
        name="Eagle Farm Logistics",
        stage="Warehouse B · Industrial",
        location="Eagle Farm, Brisbane",
        foreman="Priya Nair",
        initials="PN",
        scope="Distribution board installation",
        docket="LD-232-12",
        received="2026-10-08",
        drawing="E-110",
        variation=None,
    ),
    "INV-1046": dict(
        code="BE-241",
        name="Newstead Exchange",
        stage="Level 02 · Office fit-out",
        location="Newstead, Brisbane",
        foreman="Daniel Cruz",
        initials="DC",
        scope="Emergency lighting testing",
        docket="LD-241-11",
        received="2026-10-08",
        drawing="E-203",
        variation=None,
    ),
    "INV-1047": dict(
        code="BE-249",
        name="Paddington Retail",
        stage="Tenancy 03 · Retail fit-out",
        location="Paddington, Brisbane",
        foreman="Mia Chen",
        initials="MC",
        scope="Additional power & lighting points",
        docket="LD-249-08",
        received="2026-10-05",
        drawing="E-105 Rev C",
        variation="VO-017",
    ),
}
INVOICES = [
    (
        "INV-1042",
        "Hawthorne Projects",
        "accounts@hawthorne.example",
        840000,
        56,
        15000,
        "2026-09-21",
        0,
    ),
    (
        "INV-1043",
        "Alder Build",
        "finance@alder.example",
        630000,
        42,
        15000,
        "2026-09-25",
        0,
    ),
    (
        "INV-1044",
        "Mason & Reed",
        "billing@masonreed.example",
        360000,
        24,
        15000,
        "2026-09-29",
        0,
    ),
    (
        "INV-1045",
        "Westhaven Construction",
        "ap@westhaven.example",
        525000,
        35,
        15000,
        "2026-10-01",
        0,
    ),
    (
        "INV-1046",
        "Hawthorne Projects",
        "accounts@hawthorne.example",
        180000,
        12,
        15000,
        "2026-10-02",
        0,
    ),
    (
        "INV-1047",
        "Alder Build",
        "finance@alder.example",
        1287000,
        78,
        16500,
        "2026-09-30",
        0,
    ),
]
DOCUMENTS = [
    (
        "DOC-01",
        "INV-1042",
        "Hawthorne Projects",
        "purchase_order",
        "PO-8821 · Lighting rough-in",
        "PO-8821 authorises 56 labour hours at AUD 150/hour for Newstead Exchange, Level 02 lighting rough-in, INV-1042. Approved by Hawthorne Projects contract administrator on 9 September 2026.",
        56,
    ),
    (
        "DOC-02",
        "INV-1042",
        "Hawthorne Projects",
        "timesheet",
        "LD-241-09 · Signed labour docket",
        "Docket LD-241-09 records 56 hours of lighting rough-in at Newstead Exchange. Signed by the Hawthorne site representative on 18 September 2026. Invoice INV-1042.",
        56,
    ),
    (
        "DOC-03",
        "INV-1043",
        "Alder Build",
        "timesheet",
        "LD-238-17 · Signed labour docket",
        "Alder Build signed docket LD-238-17 for 36 hours of switchboard work at Woolloongabba Medical. INV-1043 bills 42 hours. The six additional hours have no signed docket in this record.",
        36,
    ),
    (
        "DOC-04",
        "INV-1045",
        "Westhaven Construction",
        "timesheet",
        "LD-232-12 · Signed labour docket",
        "Westhaven Construction approved 35 labour hours for distribution board installation at Eagle Farm Logistics, INV-1045.",
        35,
    ),
    (
        "DOC-05",
        "INV-1047",
        "Alder Build",
        "site_instruction",
        "SI-026 · Site instruction",
        "Site instruction SI-026 requests additional power and lighting points at Paddington Retail, drawing E-105 Rev C. This instruction does not include an approved variation price or signed VO-017.",
        None,
    ),
    (
        "DOC-06",
        "INV-1047",
        "Alder Build",
        "timesheet",
        "LD-249-08 · Signed labour docket",
        "Docket LD-249-08 records 78 hours at Paddington Retail against INV-1047. Site attendance is signed. No priced variation approval is attached.",
        78,
    ),
]
MESSAGES = [
    (
        "brace-1",
        "accounts@hawthorne.example",
        "Newstead Exchange / INV-1042 / PO reference",
        "Hi Kate,\n\nWe have the signed docket for the Level 02 lighting rough-in, but the purchase order reference is missing from INV-1042. Please send the PO so we can include it in our next payment run.\n\nEmma Walsh\nContracts administrator · Hawthorne Projects",
    ),
    (
        "brace-2",
        "finance@alder.example",
        "Woolloongabba / INV-1043 / labour discrepancy",
        "Hi Kate,\n\nOur site supervisor signed off 36 hours on LD-238-17. Your invoice shows 42 hours for the after-hours switchboard work. Can you check the extra six hours with Mia and send through the supporting docket?\n\nTom Reid\nContracts administrator · Alder Build",
    ),
    (
        "brace-3",
        "billing@masonreed.example",
        "Teneriffe Workrooms / INV-1044 / missing PO",
        "Hi Kate,\n\nWe cannot match INV-1044 to a purchase order for the data rough-in at Teneriffe. Can Daniel confirm which PO this work was ordered against?\n\nLeah Morgan\nAccounts · Mason & Reed",
    ),
    (
        "brace-4",
        "ap@westhaven.example",
        "Eagle Farm / INV-1045 / remittance",
        "Hi Kate,\n\nWe already paid INV-1045 by bank transfer yesterday. Please check the bank receipt before following up again.\n\nOliver Grant\nAccounts payable · Westhaven Construction",
    ),
    (
        "brace-5",
        "accounts@hawthorne.example",
        "Newstead Exchange / INV-1046 / invoice copy",
        "Hi Kate,\n\nCould you resend the details for INV-1046 covering the emergency lighting testing? The invoice copy is missing from our job folder.\n\nEmma Walsh\nContracts administrator · Hawthorne Projects",
    ),
    (
        "brace-6",
        "finance@alder.example",
        "Paddington / INV-1047 / variation VO-017",
        "Hi Kate,\n\nWe have the site instruction and labour docket, but there is no signed variation approval for VO-017. Please provide the approved variation for the additional power and lighting points before we assess INV-1047.\n\nTom Reid\nContracts administrator · Alder Build",
    ),
]
